/*
 * This source file was generated by the Gradle 'init' task
 */

/**
 * The main application class for configuring cars.
 */

/**
 * The main method that runs the car configuration application.
 *
 * @param args Command line arguments (not used).
 */

/**
 * Before running the application, please read the file README.md for instructions.
 */

package org.CarConfig;

import javafx.application.Application;

public class App {

    public static void main(String[] args) {
        if (System.getProperty("test.mode") == null) {
            Application.launch(UserInterface.class, args);
        }
    }
}