/*
 * This source file was generated by the Gradle 'init' task
 */
package org.CarConfig;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

class AppTest {

    private void runAppWithInput(String input) {
        InputStream originalIn = System.in;
        System.setIn(new ByteArrayInputStream(input.getBytes()));
        System.setProperty("test.mode", "true");

        try {
            String[] args = {};
            assertDoesNotThrow(() -> App.main(args));
        } finally {
            System.setIn(originalIn);
            System.clearProperty("test.mode");
        }
    }

    @Test
    void testLuxuryCarConfiguration() {
        String simulatedInput = "1\nToyota\n30000\nRed\n200\n4\n8\n8\n8\n8\n1\n1\n2\n3\n1\n";
        runAppWithInput(simulatedInput);
    }

    @Test
    void testSportsCarConfiguration() {
        String simulatedInput = "2\nFerrari\n150000\nYellow\n450\n4\n8\n8\n8\n8\n350\n1\n2\n3\n2\n";
        runAppWithInput(simulatedInput);
    }

    @Test
    void testElectricCarConfiguration() {
        String simulatedInput = "3\nTesla\n80000\nBlue\n300\n4\n7\n7\n7\n7\n90\n1\n2\n3\n1\n";
        runAppWithInput(simulatedInput);
    }

    @Test
    void testInvalidCarType() {
        String simulatedInput = "Invalid Car Type\nSTOP\n";
        runAppWithInput(simulatedInput);
    }

    @Test
    void testStopInput() {
        String simulatedInput = "STOP\n";
        runAppWithInput(simulatedInput);
    }
}